### ISSUE TITLE
Translate codes

### ISSUE THREAD

**Issue by Art34222** [leeyunjai/googletrans-python#1]
What code to translate into Chinese should I use?
![Скриншот 07-03-2023 143002](https://user-images.githubusercontent.com/127204156/223410108-f4199b7c-dc5e-42b6-baa8-401f61ff421b.jpg)

**Comment by leeyunjai82** [comment]
Hello ~

Reference to https://www.labnol.org/code/19899-google-translate-languages

>>> import googletrans as gt
>>> gt.translate("Hello", "zh-CN")
'你好'
>>> gt.translate("Hello", "zh-TW")
'你好'

**Comment by Art34222** [comment]
Okay, thanks!
